# Generated by Django 4.2.8 on 2024-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
